export const state = {
  map: null,
  mapReady: false,
  roadsVisible: true,
  roadsData: null,
  roadsMetrics: null,
  gridData: null,
  gridPointsData: null,
  gridMetricsLoaded: false,
  gridTrafficLoaded: false,
  reportRange: {
    active: false,
    vertices: [],
    polygon: null,
    gridIds: [],
  },
  reportResults: [],
  reportRangeVisible: true,
  reportRangeInteractionState: null,
  gridStats: {
    trafficMax: 0,
    populationMax: 0,
    laborMax: 0,
    floorMax: 0,
    roadAreaTotalMax: 0,
    roadAreaNatMax: 0,
    roadAreaPrefMax: 0,
    roadAreaMuniMax: 0,
    roadAreaOtherMax: 0,
  },
  addressCandidates: [],
};

export const vizThemes = {
  traffic: { label: '交通量', colors: ['#fff4e6', '#d96c3b'] },
  population: { label: '人口', colors: ['#e6f7f5', '#1b7f7a'] },
  labor: { label: '労働者数', colors: ['#edf2ff', '#475569'] },
  floor: { label: '床面積', colors: ['#fef6d8', '#b08b2e'] },
  road_area_total: { label: '合計道路面積', colors: ['#f3f1ff', '#5b4bb2'] },
  road_area_nat: { label: '国道面積', colors: ['#eef9f2', '#2f855a'] },
  road_area_pref: { label: '県道面積', colors: ['#fff4e6', '#c05621'] },
  road_area_muni: { label: '市道面積', colors: ['#ebf8ff', '#2c7a7b'] },
  road_area_other: { label: 'その他面積', colors: ['#f7fafc', '#4a5568'] },
  ratio_0_14: { label: '年齢構成（0-15）', colors: ['#eef2ff', '#1d4ed8'] },
  ratio_15_64: { label: '年齢構成（15-65）', colors: ['#ecfeff', '#0f766e'] },
  ratio_65_over: { label: '年齢構成（65以上）', colors: ['#fff7ed', '#c2410c'] },
  score: { label: '必要度スコア', colors: ['#f0f4ff', '#2b4f9c'] },
  none: { label: '選択なし', colors: ['transparent', 'transparent'] },
};
